### ISSUE TITLE
vyřaďte Extstock.com z https://kurzy.gwei.cz

### ISSUE THREAD

**Issue by Huge** [gweicz/docs#7]
Váš srovnávač burz a směnáren dává pěkný přehled, nicméně navrhuju vyřadit _**ExtStock**_ skrz špatné reference na  https://www.trustpilot.com/review/extstock.com , jež potvrzují i podezřelé odchylky v středním kurzu od ostatních trhů.

**Comment by burningtree** [comment]
@Huge Vyřazeno už delší dobu, díky za feedback!
